---

- name: Install bat
  become: yes
  apt:
    name: bat
    update_cache: yes

- name: Make directory
  file:
    path: $HOME/.local/bin
    state: directory

- name: Make synmlink
  file:
    src: /usr/bin/batcat 
    dest: $HOME/.local/bin/bat
    state: link
