---

- name: Install vim
  become: yes
  apt:
    name:
      - git
      - curl
      - vim
    update_cache: yes

- name: Install vim-plug
  shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  args:
    executable: /bin/bash

- name: make config directory
  file:
    path: $HOME/.vim/_config
    state: directory

# https://mattn.kaoriya.net/software/vim/20191231213507.htm
- name: Copy config of mattn's vim
  template:
    src: ./roles/vim/templates/200-lsp.vim.j2
    dest: $HOME/.vim/_config/200-lsp.vim

- name: Install color scheme
  git:
    repo: https://github.com/tomasr/molokai
    dest: $HOME/.vim/colors/molokai
    force: yes

- name: Move color scheme
  shell: mv $HOME/.vim/colors/molokai/colors/molokai.vim $HOME/.vim/colors/ && rm -rf $HOME/.vim/colors/molokai/
